# serverless.yml

custom:
  serviceName: Route53Updater
service:
  name: ${self:custom.serviceName}
  awsKmsKeyArn: arn:aws:kms:us-east-1:257953708933:key/b9cb1425-986a-4aec-9a83-72cdc6dba044

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev # Set the default stage used. Default is dev
  region: us-east-1 # Overwrite the default region used. Default is us-east-1
  stackName: ${self:custom.serviceName}-stack # Use a custom name for the CloudFormation stack
  apiName: ${self:custom.serviceName}-api # Use a custom name for the API Gateway API
  # profile: production # The default AWS profile to use with this service
  # memorySize: 128 # Overwrite the default memory size. Default is 1024 -- defined on each function
  timeout: 10 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 1 # Set the default RetentionInDays for a CloudWatch LogGroup
  deploymentBucket:
    name: apogee-lambda-deploy # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  versionFunctions: false # Optional function versioning
  endpointType: regional # Optional endpoint configuration for API Gateway REST API. Default is Edge.

  usagePlan: # Optional usage plan configuration
    quota:
      limit: 2500
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 100
      rateLimit: 50
  stackTags: # Optional CF stack tags
    key: value

package:
  artifact: ../dist/lambda/route53updater.zip
  individually: true
  excludeDevDependencies: true

functions:
  updater:
    handler: route53updater
    name: ${self:custom.serviceName}-${self:provider.stage}-updater
    description: Route53 domain updater
    memorySize: 128
    events:
      - http:
          path: /
          method: post
          cors: false